using System;
using System.Collections.Generic;

namespace Lumoin.Veridical.Analysis.StatisticalTests;

/// <summary>
/// Permutation tests: two-sample comparisons whose null distribution is
/// generated by relabeling the observed units instead of assumed
/// analytically. This is the valid form when the units' internal structure
/// breaks an analytic test's independence assumptions — the batch SM
/// finding: proof bytes are heavily dependent within one proof (shared
/// digests, repeated scalars), so the analytic chi-squared p-value rejects
/// even witness-independent labelings, while the label-permutation null
/// compares like with like.
/// </summary>
public static class PermutationTest
{
    //199 relabelings give the permutation p-value a resolution of
    //1/200 = 0.005 at modest cost (each permutation only re-pools the
    //precomputed per-unit histograms).
    public const int DefaultPermutationCount = 199;

    //A fixed xorshift seed: the permutation null needs reproducibility
    //across runs.
    public const ulong DefaultSeed = 0x5DEECE66DUL;


    /// <summary>
    /// Tests whether the per-unit histograms of two labeled classes pool to
    /// the same distribution, using the chi-squared homogeneity statistic
    /// with a label-permutation null: the observed statistic is ranked
    /// against the same statistic under <paramref name="permutationCount"/>
    /// class-size-preserving relabelings,
    /// <c>p = (1 + #{permuted ≥ observed}) / (count + 1)</c>.
    /// </summary>
    /// <param name="histograms">One histogram per unit (for example one byte-value histogram per proof); all the same length.</param>
    /// <param name="labels">The class label (0 or 1) of each unit.</param>
    /// <param name="permutationCount">The number of relabelings to draw.</param>
    /// <param name="seed">The xorshift seed for the relabeling stream.</param>
    /// <param name="significanceLevel">The rejection threshold for the permutation p-value.</param>
    /// <returns>
    /// The result whose statistic is the observed chi-squared homogeneity
    /// value and whose p-value is the permutation p-value; inconclusive when
    /// only one class is present.
    /// </returns>
    /// <exception cref="ArgumentNullException">When a reference argument is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">When the label count does not match the histogram count.</exception>
    public static StatisticalTestResult HomogeneityOfPooledHistograms(
        IReadOnlyList<long[]> histograms,
        ReadOnlySpan<int> labels,
        int permutationCount = DefaultPermutationCount,
        ulong seed = DefaultSeed,
        double significanceLevel = 0.05)
    {
        ArgumentNullException.ThrowIfNull(histograms);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(permutationCount);
        if(labels.Length != histograms.Count)
        {
            throw new ArgumentException($"Received {labels.Length} labels for {histograms.Count} histograms.", nameof(labels));
        }

        int countOne = 0;
        for(int i = 0; i < labels.Length; i++)
        {
            countOne += labels[i];
        }

        if(countOne == 0 || countOne == labels.Length)
        {
            return StatisticalTestResult.Inconclusive(significanceLevel);
        }

        var workingLabels = new int[labels.Length];
        labels.CopyTo(workingLabels);
        double observed = PooledStatistic(histograms, workingLabels, significanceLevel);

        ulong state = seed;
        int atLeastAsExtreme = 0;
        for(int permutation = 0; permutation < permutationCount; permutation++)
        {
            Shuffle(workingLabels, ref state);
            if(PooledStatistic(histograms, workingLabels, significanceLevel) >= observed)
            {
                atLeastAsExtreme++;
            }
        }

        double permutationP = (1.0 + atLeastAsExtreme) / (permutationCount + 1.0);

        return StatisticalTestResult.Decisive(observed, degreesOfFreedom: null, permutationP, significanceLevel);
    }


    //The chi-squared homogeneity statistic of the two class-pooled histograms
    //under the given labeling. Only the statistic is used — its analytic
    //p-value is invalid under intra-unit dependence (see the type remarks).
    private static double PooledStatistic(IReadOnlyList<long[]> histograms, int[] labels, double significanceLevel)
    {
        int binCount = histograms[0].Length;
        long[] classZero = new long[binCount];
        long[] classOne = new long[binCount];
        for(int i = 0; i < histograms.Count; i++)
        {
            long[] target = labels[i] == 0 ? classZero : classOne;
            VectorizedAccumulation.AddInPlace(target, histograms[i]);
        }

        return ChiSquaredTest.Homogeneity(classZero, classOne, significanceLevel).TestStatistic;
    }


    //Fisher–Yates over the label vector with a xorshift64 step — deterministic,
    //reproducible, and statistically ample for a permutation null.
    private static void Shuffle(int[] labels, ref ulong state)
    {
        for(int i = labels.Length - 1; i >= 1; i--)
        {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            int j = (int)(state % (ulong)(i + 1));
            (labels[i], labels[j]) = (labels[j], labels[i]);
        }
    }
}
