using Lumoin.Veridical.Backends.Managed;
using Lumoin.Veridical.Core;
using Lumoin.Veridical.Core.Algebraic;
using Lumoin.Veridical.Core.Commitments;
using Lumoin.Veridical.Core.ConstraintSystems;
using Lumoin.Veridical.Core.ConstraintSystems.Interop;
using Lumoin.Veridical.Core.ConstraintSystems.Interop.ZkInterface;
using Lumoin.Veridical.Core.Memory;
using Lumoin.Veridical.Core.Spartan;
using Lumoin.Veridical.Tests.Algebraic;
using Lumoin.Veridical.Tests.TestInfrastructure;
using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.IO.Pipelines;
using System.Numerics;
using System.Threading;

namespace Lumoin.Veridical.Tests.ConstraintSystems.Interop.ZkInterface;

/// <summary>
/// Real-fixture gate: independently produced <c>.zkif</c> files parse
/// through the Veridical instance and witness readers and satisfy
/// <c>A·z ∘ B·z = C·z</c> in the curve's scalar arithmetic. Because the
/// bytes were not generated by Veridical's own serializer, this is a
/// genuine interop check of the hand-written FlatBuffers reader, not a
/// round-trip self-test.
/// </summary>
/// <remarks>
/// The fixture is the padded multiplier2 (<c>a·b = c</c> plus a <c>1·1 = 1</c>
/// row): public output <c>c</c> in <c>instance_variables</c>, private
/// <c>a, b</c> in the witness, satisfied by <c>a = 3, b = 11, c = 33</c>.
/// The shape (2 constraints, 4 variables) is a power of two, so the parsed
/// instance also feeds the Spartan prover.
/// </remarks>
[TestClass]
internal sealed class ZkInterfaceFixtureTests
{
    /// <summary>The fixture directory, relative to the test output, holding the per-curve ZkInterface fixture files.</summary>
    private const string FixtureDirectoryRelative = "ConstraintSystems/Interop/ZkInterface/Fixtures";

    /// <summary>The constraint row count of the padded multiplier2 fixture: the <c>a·b = c</c> row plus the <c>1·1 = 1</c> padding row.</summary>
    private const int ExpectedRowCount = 2;

    /// <summary>The variable column count of the padded multiplier2 fixture: the constant column plus <c>a</c>, <c>b</c>, and <c>c</c>.</summary>
    private const int ExpectedColumnCount = 4;

    /// <summary>The witness variable count of the padded multiplier2 fixture: <c>a</c>, <c>b</c>, and <c>c</c>, excluding the constant column.</summary>
    private const int ExpectedWitnessVariableCount = 3;


    /// <summary>Verifies that the BLS12-381 multiplier2 fixture parses and satisfies its constraints under the curve's scalar arithmetic.</summary>
    [TestMethod]
    public void Bls12Curve381Multiplier2FixtureParsesAndSatisfies()
    {
        ExerciseFixture(
            "bls12_381",
            CurveParameterSet.Bls12Curve381,
            Bls12Curve381BigIntegerScalarReference.GetAdd(),
            Bls12Curve381BigIntegerScalarReference.GetMultiply());
    }


    /// <summary>Verifies that the BN254 multiplier2 fixture parses and satisfies its constraints under the curve's scalar arithmetic.</summary>
    [TestMethod]
    public void Bn254Multiplier2FixtureParsesAndSatisfies()
    {
        ExerciseFixture(
            "bn254",
            CurveParameterSet.Bn254,
            Bn254BigIntegerScalarReference.GetAdd(),
            Bn254BigIntegerScalarReference.GetMultiply());
    }


    /// <summary>Loads <paramref name="curveDirectory"/>'s fixture, parses its instance and witness, and asserts that the parsed shape and satisfaction match the padded multiplier2 fixture.</summary>
    /// <param name="curveDirectory">The fixture subdirectory naming the curve, matching the committed fixture layout.</param>
    /// <param name="curve">The curve the fixture bytes are declared under.</param>
    /// <param name="add">The reference scalar addition used to check satisfaction.</param>
    /// <param name="multiply">The reference scalar multiplication used to check satisfaction.</param>
    private static void ExerciseFixture(string curveDirectory, CurveParameterSet curve, ScalarAddDelegate add, ScalarMultiplyDelegate multiply)
    {
        byte[] fixtureBytes = LoadFixtureBytes(curveDirectory);

        using RawR1csInstance instance = ParseInstance(fixtureBytes, curve);
        using RawR1csWitness witness = ParseWitness(fixtureBytes, curve);

        Assert.AreEqual(ExpectedRowCount, instance.A.RowCount, "A.RowCount");
        Assert.AreEqual(ExpectedColumnCount, instance.A.ColumnCount, "A.ColumnCount");
        Assert.AreEqual(0, instance.PublicInputCount, "PublicInputCount");
        Assert.AreEqual(ExpectedWitnessVariableCount, witness.WitnessVariableCount, "WitnessVariableCount");
        Assert.AreEqual(curve.Code, instance.Curve.Code, "parsed instance curve");

        using R1csSatisfaction satisfaction = instance.CheckSatisfiedBy(witness, add, multiply, BaseMemoryPool.Shared);

        if(satisfaction is R1csSatisfaction.Violated violated)
        {
            Assert.Fail($"ZkInterface fixture ({curveDirectory}) satisfaction failed at constraint {violated.ConstraintIndex.Value}.");
        }

        Assert.IsInstanceOfType<R1csSatisfaction.Satisfied>(satisfaction);
    }


    /// <summary>Reads the multiplier2 fixture bytes for <paramref name="curveDirectory"/>, falling back to a project-relative path when the test host does not copy the output-relative fixture folder.</summary>
    /// <param name="curveDirectory">The fixture subdirectory naming the curve.</param>
    private static byte[] LoadFixtureBytes(string curveDirectory)
    {
        string directory = Path.Combine(AppContext.BaseDirectory, FixtureDirectoryRelative, curveDirectory);
        if(!Directory.Exists(directory))
        {
            directory = Path.Combine(FixtureDirectoryRelative, curveDirectory);
        }

        string path = Path.Combine(directory, "multiplier2.zkif");
        if(!File.Exists(path))
        {
            Assert.Inconclusive($"Fixture file not found: {path}. Restore the committed fixture bytes.");
        }

        return File.ReadAllBytes(path);
    }


    /// <summary>Verifies that the parsed-from-real-bytes BLS12-381 multiplier2 instance is also prover-ready: it proves and verifies end-to-end through the base Spartan prover and verifier.</summary>
    [TestMethod]
    public void Bls12Curve381Multiplier2FixtureProvesAndVerifiesWithSpartan()
    {
        byte[] fixtureBytes = LoadFixtureBytes("bls12_381");

        using RawR1csWitness witness = ParseWitness(fixtureBytes, CurveParameterSet.Bls12Curve381);
        using SpartanProver prover = BuildBaseProver(ExpectedColumnCount);
        using SpartanVerifier verifier = BuildBaseVerifier(ExpectedColumnCount);

        using RawR1csInstance proverInstance = ParseInstance(fixtureBytes, CurveParameterSet.Bls12Curve381);
        using RawR1csInstance verifierInstance = ParseInstance(fixtureBytes, CurveParameterSet.Bls12Curve381);

        using FiatShamirTranscript proverTranscript = FreshTranscript();
        using SpartanProof proof = prover.Prove(
            proverInstance, witness, proverTranscript,
            Hash, Squeeze, Reduce, Add, Subtract, Multiply, Invert, ScalarRandom,
            G1Add, G1ScalarMul, G1Msm, MleEvaluate, MleFold,
            BaseMemoryPool.Shared);

        using FiatShamirTranscript verifierTranscript = FreshTranscript();
        bool verified = verifier.Verify(
            proof, verifierInstance, verifierTranscript,
            Add, Multiply, Subtract, Invert, Reduce,
            G1Add, G1ScalarMul, G1Msm, Hash, Squeeze,
            BaseMemoryPool.Shared);

        Assert.IsTrue(verified, "Spartan failed to verify a ZkInterface-parsed multiplier2 instance.");
    }


    /// <summary>Parses the R1CS instance from a raw ZkInterface byte buffer, with no intake ceiling.</summary>
    /// <param name="bytes">The complete ZkInterface stream bytes.</param>
    /// <param name="curve">The curve the instance is declared under.</param>
    private static RawR1csInstance ParseInstance(byte[] bytes, CurveParameterSet curve)
    {
        var stream = new MemoryStream(bytes, writable: false);
        PipeReader pipe = PipeReader.Create(stream);

        return ZkInterfaceR1csReader.Reader(pipe, WellKnownR1csFormatLabel.ZkInterface, curve, BaseMemoryPool.Shared, WellKnownR1csIntakeLimits.Unbounded, CancellationToken.None);
    }


    /// <summary>Parses the R1CS witness from a raw ZkInterface byte buffer, with no intake ceiling.</summary>
    /// <param name="bytes">The complete ZkInterface stream bytes.</param>
    /// <param name="curve">The curve the witness is declared under.</param>
    private static RawR1csWitness ParseWitness(byte[] bytes, CurveParameterSet curve)
    {
        var stream = new MemoryStream(bytes, writable: false);
        PipeReader pipe = PipeReader.Create(stream);

        return ZkInterfaceWitnessReader.Reader(pipe, WellKnownR1csFormatLabel.ZkInterface, curve, BaseMemoryPool.Shared, WellKnownR1csIntakeLimits.Unbounded, CancellationToken.None);
    }


    /// <summary>Builds a base Spartan prover over a freshly derived commitment key sized for <paramref name="columnCount"/>.</summary>
    /// <param name="columnCount">The R1CS column count the commitment key must accommodate.</param>
    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership of intermediate disposables transfers to the returned SpartanProver via its constructor chain.")]
    private static SpartanProver BuildBaseProver(int columnCount)
    {
        var provingKey = new SpartanProvingKey(BuildProvider(BuildCommitmentKey(columnCount)));

        return new SpartanProver(provingKey);
    }


    /// <summary>Builds a base Spartan verifier over a freshly derived commitment key sized for <paramref name="columnCount"/>.</summary>
    /// <param name="columnCount">The R1CS column count the commitment key must accommodate.</param>
    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership of intermediate disposables transfers to the returned SpartanVerifier via its constructor chain.")]
    private static SpartanVerifier BuildBaseVerifier(int columnCount)
    {
        var verifyingKey = new SpartanVerifyingKey(BuildProvider(BuildCommitmentKey(columnCount)));

        return new SpartanVerifier(verifyingKey);
    }


    /// <summary>Wraps <paramref name="commitmentKey"/> in a Hyrax polynomial commitment provider over the BLS12-381 curve, taking ownership of the key.</summary>
    /// <param name="commitmentKey">The commitment key the provider takes ownership of.</param>
    [SuppressMessage("Reliability", "CA2000", Justification = "The provider takes ownership of the key (ownsKey: true) and transfers to the Spartan key that consumes it.")]
    private static PolynomialCommitmentProvider BuildProvider(HyraxCommitmentKey commitmentKey)
    {
        return HyraxPolynomialCommitmentScheme.Create(
            commitmentKey,
            CurveParameterSet.Bls12Curve381,
            Hash, Squeeze, Reduce, Add, Subtract, Multiply, Invert, ScalarRandom,
            G1Add, G1ScalarMul, G1Msm, G1IsOnCurve, G1IsInPrimeOrderSubgroup,
            ownsKey: true);
    }


    /// <summary>Derives a Hyrax commitment key sized to the smallest power of two accommodating <paramref name="columnCount"/> columns.</summary>
    /// <param name="columnCount">The R1CS column count the derived key must accommodate.</param>
    private static HyraxCommitmentKey BuildCommitmentKey(int columnCount)
    {
        int columnVariableCount = BitOperations.Log2((uint)columnCount);
        HyraxCommitmentDimensions commitmentDims = HyraxCommitmentDimensions.ForVariableCount(columnVariableCount);

        return HyraxCommitmentKey.Derive(
            commitmentDims.ColumnCount,
            WellKnownHyraxDomainLabels.CanonicalSeedV1,
            CurveParameterSet.Bls12Curve381,
            HashToCurve,
            BaseMemoryPool.Shared);
    }


    /// <summary>Initialises a fresh Fiat-Shamir transcript under the Spartan v1 domain label, ready for a single prove or verify pass.</summary>
    private static FiatShamirTranscript FreshTranscript()
    {
        return FiatShamirTranscript.Initialise(
            new FiatShamirDomainLabel(WellKnownSpartanDomainLabels.SpartanV1),
            ReadOnlySpan<byte>.Empty,
            WellKnownHashAlgorithms.Blake3,
            Hash,
            BaseMemoryPool.Shared);
    }


    /// <summary>The Blake3 hash delegate used to drive the Fiat-Shamir transcript.</summary>
    private static FiatShamirHashDelegate Hash { get; } = FiatShamirBlake3Reference.GetHash();

    /// <summary>The Blake3 squeeze delegate used to draw challenges from the Fiat-Shamir transcript.</summary>
    private static FiatShamirSqueezeDelegate Squeeze { get; } = FiatShamirBlake3Reference.GetSqueeze();

    /// <summary>The reference scalar reduction for BLS12-381, used to canonicalise field elements.</summary>
    private static ScalarReduceDelegate Reduce { get; } = Bls12Curve381BigIntegerScalarReference.GetReduce();

    /// <summary>The reference scalar addition for BLS12-381.</summary>
    private static ScalarAddDelegate Add { get; } = Bls12Curve381BigIntegerScalarReference.GetAdd();

    /// <summary>The reference scalar subtraction for BLS12-381.</summary>
    private static ScalarSubtractDelegate Subtract { get; } = Bls12Curve381BigIntegerScalarReference.GetSubtract();

    /// <summary>The reference scalar multiplication for BLS12-381.</summary>
    private static ScalarMultiplyDelegate Multiply { get; } = Bls12Curve381BigIntegerScalarReference.GetMultiply();

    /// <summary>The reference scalar inversion for BLS12-381.</summary>
    private static ScalarInvertDelegate Invert { get; } = Bls12Curve381BigIntegerScalarReference.GetInvert();

    /// <summary>The reference scalar random-sampling delegate for BLS12-381.</summary>
    private static ScalarRandomDelegate ScalarRandom { get; } = Bls12Curve381BigIntegerScalarReference.GetRandom();

    /// <summary>The reference G1 point addition for BLS12-381.</summary>
    private static G1AddDelegate G1Add { get; } = Bls12Curve381BigIntegerG1Reference.GetAdd();

    /// <summary>The reference G1 scalar multiplication for BLS12-381.</summary>
    private static G1ScalarMultiplyDelegate G1ScalarMul { get; } = Bls12Curve381BigIntegerG1Reference.GetScalarMultiply();

    /// <summary>The multi-scalar-multiplication backend for BLS12-381 exercised by these tests.</summary>
    private static G1MultiScalarMultiplyDelegate G1Msm { get; } = TestG1Backends.Bls12Curve381Msm;

    /// <summary>The reference G1 curve-membership check for BLS12-381.</summary>
    private static G1IsOnCurveDelegate G1IsOnCurve { get; } = Bls12Curve381BigIntegerG1Reference.GetIsOnCurve();

    /// <summary>The reference G1 prime-order-subgroup check for BLS12-381.</summary>
    private static G1IsInPrimeOrderSubgroupDelegate G1IsInPrimeOrderSubgroup { get; } = Bls12Curve381BigIntegerG1Reference.GetIsInPrimeOrderSubgroup();

    /// <summary>The reference hash-to-curve delegate for BLS12-381, used to derive the commitment key's generators.</summary>
    private static G1HashToCurveDelegate HashToCurve { get; } = Bls12Curve381BigIntegerG1Reference.GetHashToCurve();

    /// <summary>The reference multilinear-extension evaluation delegate.</summary>
    private static MleEvaluateDelegate MleEvaluate { get; } = MultilinearExtensionBigIntegerReference.GetEvaluate();

    /// <summary>The reference multilinear-extension folding delegate.</summary>
    private static MleFoldDelegate MleFold { get; } = MultilinearExtensionBigIntegerReference.GetFold();
}
