using Lumoin.Veridical.Core;
using Lumoin.Veridical.Core.Algebraic;
using Lumoin.Veridical.Core.Commitments;
using Lumoin.Veridical.Core.ConstraintSystems;
using Lumoin.Veridical.Core.Memory;
using Lumoin.Veridical.Core.Spartan;
using Lumoin.Veridical.Tests.Algebraic;
using Lumoin.Veridical.Tests.TestInfrastructure;
using System;
using System.Buffers;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Numerics;
using System.Text;

namespace Lumoin.Veridical.Tests.Spartan;

/// <summary>
/// Regression test against a committed wire-format fixture for the
/// <c>x · y = 15</c> circuit. The fixture protects against silent
/// changes in the proof byte layout: if a future change accidentally
/// alters the wire format, these tests fail and point at the drift.
/// </summary>
/// <remarks>
/// <para>
/// The fixture is generated by the test
/// <see cref="RegenerateFixture"/> (gated by an explicit environment
/// variable so it does not run in normal CI). The committed fixture
/// files live in <c>Spartan/Fixtures/xy-equals-15/</c>.
/// </para>
/// </remarks>
[TestClass]
internal sealed class SpartanFixtureTests
{
    private static FiatShamirHashDelegate Hash { get; } = FiatShamirBlake3Reference.GetHash();
    private static FiatShamirSqueezeDelegate Squeeze { get; } = FiatShamirBlake3Reference.GetSqueeze();
    private static ScalarReduceDelegate Reduce { get; } = Bls12Curve381BigIntegerScalarReference.GetReduce();
    private static ScalarAddDelegate Add { get; } = Bls12Curve381BigIntegerScalarReference.GetAdd();
    private static ScalarSubtractDelegate Subtract { get; } = Bls12Curve381BigIntegerScalarReference.GetSubtract();
    private static ScalarMultiplyDelegate Multiply { get; } = Bls12Curve381BigIntegerScalarReference.GetMultiply();
    private static ScalarInvertDelegate Invert { get; } = Bls12Curve381BigIntegerScalarReference.GetInvert();
    private static G1AddDelegate G1Add { get; } = Bls12Curve381BigIntegerG1Reference.GetAdd();
    private static G1ScalarMultiplyDelegate G1ScalarMul { get; } = Bls12Curve381BigIntegerG1Reference.GetScalarMultiply();
    private static G1MultiScalarMultiplyDelegate G1Msm { get; } = TestG1Backends.Bls12Curve381Msm;
    private static G1HashToCurveDelegate HashToCurve { get; } = Bls12Curve381BigIntegerG1Reference.GetHashToCurve();
    private static MleEvaluateDelegate MleEvaluate { get; } = MultilinearExtensionBigIntegerReference.GetEvaluate();
    private static MleFoldDelegate MleFold { get; } = MultilinearExtensionBigIntegerReference.GetFold();

    //Fixed seed for the deterministic RNG so the fixture is reproducible.
    private static byte[] FixtureRandomSeed { get; } = Encoding.UTF8.GetBytes("veridical.spartan.fixture.xy-equals-15.v1");

    private const string FixtureDirectoryRelative = "Spartan/Fixtures/xy-equals-15";
    private const string InstanceFileName = "instance.bin";
    private const string WitnessFileName = "witness.bin";
    private const string ProofFileName = "proof.bin";
    private const string TranscriptDomainFileName = "transcript-domain.txt";
    private const string ExpectedDomain = "veridical.spartan2.v1";


    [TestMethod]
    [SuppressMessage("Reliability", "CA2000", Justification = "DeserialiseInstance's ownership transfers through using declarations; final disposal happens before the assertion completes.")]
    public void XyEquals15FixtureProofVerifies()
    {
        string fixturePath = ResolveFixturePath();
        if(!Directory.Exists(fixturePath))
        {
            Assert.Inconclusive(
                $"Fixture directory {fixturePath} not found. Run RegenerateFixture once with the VERIDICAL_REGENERATE_FIXTURES environment variable set to populate the fixture, then commit the bytes.");
        }

        byte[] instanceBytes = File.ReadAllBytes(Path.Combine(fixturePath, InstanceFileName));
        byte[] witnessBytes = File.ReadAllBytes(Path.Combine(fixturePath, WitnessFileName));
        byte[] proofBytes = File.ReadAllBytes(Path.Combine(fixturePath, ProofFileName));
        string domain = File.ReadAllText(Path.Combine(fixturePath, TranscriptDomainFileName)).Trim();
        Assert.AreEqual(ExpectedDomain, domain);

        using RawR1csInstance instance = DeserialiseInstance(instanceBytes);
        using RawR1csWitness witness = DeserialiseWitness(witnessBytes, instance);
        using SpartanProof proof = DeserialiseProof(proofBytes, instance);

        using SpartanVerifier verifier = BuildVerifier();
        using RawR1csInstance verifierInstance = DeserialiseInstance(instanceBytes);
        using FiatShamirTranscript transcript = FreshTranscript(domain);
        bool verified = verifier.Verify(
            proof, verifierInstance, transcript,
            Add, Multiply, Subtract, Invert, Reduce,
            G1Add, G1ScalarMul, G1Msm, Hash, Squeeze,
            SensitiveMemoryPool<byte>.Shared);

        Assert.IsTrue(verified, "The committed xy=15 fixture proof must verify.");
    }


    [TestMethod]
    public void CSharpProverProducesByteIdenticalFixtureProof()
    {
        string fixturePath = ResolveFixturePath();
        if(!Directory.Exists(fixturePath))
        {
            Assert.Inconclusive(
                $"Fixture directory {fixturePath} not found. Run RegenerateFixture once with the VERIDICAL_REGENERATE_FIXTURES environment variable set to populate the fixture, then commit the bytes.");
        }

        byte[] expectedProofBytes = File.ReadAllBytes(Path.Combine(fixturePath, ProofFileName));

        using SpartanProof regeneratedProof = ProduceFixtureProof();
        byte[] actualProofBytes = regeneratedProof.AsReadOnlySpan().ToArray();

        Assert.HasCount(
            expectedProofBytes.Length,
            actualProofBytes,
            "Regenerated proof byte length differs from the committed fixture.");
        Assert.IsTrue(
            expectedProofBytes.AsSpan().SequenceEqual(actualProofBytes),
            "Regenerated proof bytes differ from the committed fixture. Either the prover's wire format drifted (regenerate intentionally) or non-determinism leaked into the prover path (a bug).");
    }


    [TestMethod]
    public void RegenerateFixture()
    {
        //Gated by an env var so the fixture is only regenerated when
        //deliberately requested. The committed fixture is consumed by
        //the two verification tests above; this method writes a fresh
        //copy when the env var is set.
        string? regenerate = Environment.GetEnvironmentVariable("VERIDICAL_REGENERATE_FIXTURES");
        if(string.IsNullOrEmpty(regenerate))
        {
            Assert.Inconclusive("Set VERIDICAL_REGENERATE_FIXTURES=1 to enable fixture regeneration.");
            return;
        }

        string fixturePath = ResolveSourceFixturePath();
        Directory.CreateDirectory(fixturePath);

        using RawR1csInstance instance = BuildFixtureInstance();
        using RawR1csWitness witness = BuildFixtureWitness();
        using SpartanProof proof = ProduceFixtureProof();

        File.WriteAllBytes(Path.Combine(fixturePath, InstanceFileName), SerialiseInstance(instance));
        File.WriteAllBytes(Path.Combine(fixturePath, WitnessFileName), witness.GetWitnessBytes().ToArray());
        File.WriteAllBytes(Path.Combine(fixturePath, ProofFileName), proof.AsReadOnlySpan().ToArray());
        File.WriteAllText(Path.Combine(fixturePath, TranscriptDomainFileName), ExpectedDomain + "\n");
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership transfers through using declarations and the returned SpartanProof.")]
    private static SpartanProof ProduceFixtureProof()
    {
        using RawR1csInstance instance = BuildFixtureInstance();
        HyraxCommitmentKey commitmentKey = HyraxCommitmentKey.Derive(
            2,
            WellKnownHyraxDomainLabels.CanonicalSeedV1,
            CurveParameterSet.Bls12Curve381,
            HashToCurve,
            SensitiveMemoryPool<byte>.Shared);

        //The provider's commit/open close over the random delegate that supplies
        //the Hyrax blinding factors, so it must be the same deterministic RNG the
        //proof's blinding draws from to keep the fixture bytes byte-identical.
        var rng = new DeterministicScalarRandom(FixtureRandomSeed);
        ScalarRandomDelegate random = rng.AsDelegate();
        var provingKey = new SpartanProvingKey(BuildProvider(commitmentKey, random));
        using var prover = new SpartanProver(provingKey);
        using RawR1csWitness witness = BuildFixtureWitness();
        using FiatShamirTranscript transcript = FreshTranscript(ExpectedDomain);

        return prover.Prove(
            instance, witness, transcript,
            Hash, Squeeze, Reduce, Add, Subtract, Multiply, Invert, random,
            G1Add, G1ScalarMul, G1Msm, MleEvaluate, MleFold,
            SensitiveMemoryPool<byte>.Shared);
    }


    /// <summary>
    /// The fixture circuit: <c>x · y = target</c> with <c>target</c> as a
    /// public input. z = (1, target, x, y), m = 2 (one real constraint + one
    /// trivial padding constraint <c>z[0]·z[0] = z[0]</c>).
    /// </summary>
    private static RawR1csInstance BuildFixtureInstance()
    {
        int scalarSize = Scalar.SizeBytes;
        int[] aRows = [0, 1];
        int[] aCols = [2, 0];
        int[] bRows = [0, 1];
        int[] bCols = [3, 0];
        int[] cRows = [0, 1];
        int[] cCols = [1, 0];

        byte[] onesValues = new byte[2 * scalarSize];
        WriteCanonical(BigInteger.One, onesValues.AsSpan(0, scalarSize));
        WriteCanonical(BigInteger.One, onesValues.AsSpan(scalarSize, scalarSize));

        R1csMatrix a = R1csMatrix.FromSortedTriples(aRows, aCols, onesValues, 2, 4, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
        R1csMatrix b = R1csMatrix.FromSortedTriples(bRows, bCols, onesValues, 2, 4, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
        R1csMatrix c = R1csMatrix.FromSortedTriples(cRows, cCols, onesValues, 2, 4, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);

        byte[] publicInput = new byte[scalarSize];
        WriteCanonical(new BigInteger(15), publicInput);

        return RawR1csInstance.Create(a, b, c, publicInput, SensitiveMemoryPool<byte>.Shared);
    }


    private static RawR1csWitness BuildFixtureWitness()
    {
        //Witness: x=3, y=5. z = (1, 15, 3, 5). c0: 3·5 = 15 ✓. c1: 1·1 = 1 ✓.
        int scalarSize = Scalar.SizeBytes;
        byte[] witnessBytes = new byte[2 * scalarSize];
        WriteCanonical(new BigInteger(3), witnessBytes.AsSpan(0 * scalarSize, scalarSize));
        WriteCanonical(new BigInteger(5), witnessBytes.AsSpan(1 * scalarSize, scalarSize));
        return RawR1csWitness.FromCanonical(witnessBytes, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership transfers through chained constructors to the returned SpartanVerifier.")]
    private static SpartanVerifier BuildVerifier()
    {
        HyraxCommitmentKey commitmentKey = HyraxCommitmentKey.Derive(
            2,
            WellKnownHyraxDomainLabels.CanonicalSeedV1,
            CurveParameterSet.Bls12Curve381,
            HashToCurve,
            SensitiveMemoryPool<byte>.Shared);
        //Verification never draws blinding factors, so the random backend the
        //provider closes over is immaterial here; a deterministic one keeps it pure.
        var verifyingKey = new SpartanVerifyingKey(BuildProvider(commitmentKey, new DeterministicScalarRandom(FixtureRandomSeed).AsDelegate()));

        return new SpartanVerifier(verifyingKey);
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "The provider takes ownership of the key (ownsKey: true) and transfers to the Spartan key that consumes it.")]
    private static PolynomialCommitmentProvider BuildProvider(HyraxCommitmentKey commitmentKey, ScalarRandomDelegate random)
    {
        return HyraxPolynomialCommitmentScheme.Create(
            commitmentKey,
            CurveParameterSet.Bls12Curve381,
            Hash, Squeeze, Reduce, Add, Subtract, Multiply, Invert, random,
            G1Add, G1ScalarMul, G1Msm,
            ownsKey: true);
    }


    private static FiatShamirTranscript FreshTranscript(string domain)
    {
        return FiatShamirTranscript.Initialise(
            new FiatShamirDomainLabel(domain),
            ReadOnlySpan<byte>.Empty,
            WellKnownHashAlgorithms.Blake3,
            Hash,
            SensitiveMemoryPool<byte>.Shared);
    }


    private static string ResolveFixturePath()
    {
        //Test binaries copy fixture files alongside the dll; FixtureDirectoryRelative
        //is the relative path from the test output folder.
        string baseDir = AppContext.BaseDirectory;
        return Path.Combine(baseDir, FixtureDirectoryRelative);
    }


    private static string ResolveSourceFixturePath()
    {
        //For the regeneration helper, write directly into the source
        //tree so the regenerated bytes can be inspected and committed.
        string baseDir = AppContext.BaseDirectory;
        DirectoryInfo? current = new DirectoryInfo(baseDir);
        while(current is not null && !File.Exists(Path.Combine(current.FullName, "Lumoin.Veridical.Tests.csproj")))
        {
            current = current.Parent;
        }
        if(current is null)
        {
            throw new InvalidOperationException("Could not locate the test project root from AppContext.BaseDirectory.");
        }

        return Path.Combine(current.FullName, FixtureDirectoryRelative);
    }


    private static byte[] SerialiseInstance(RawR1csInstance instance)
    {
        using MemoryStream ms = new();
        Span<byte> intBuffer = stackalloc byte[sizeof(int)];

        WriteInt(ms, intBuffer, instance.A.RowCount);
        WriteInt(ms, intBuffer, instance.A.ColumnCount);
        WriteInt(ms, intBuffer, instance.PublicInputCount);
        SerialiseMatrix(ms, instance.A, intBuffer);
        SerialiseMatrix(ms, instance.B, intBuffer);
        SerialiseMatrix(ms, instance.C, intBuffer);
        ms.Write(instance.GetPublicInputsBytes());
        return ms.ToArray();
    }


    private static void SerialiseMatrix(MemoryStream destination, R1csMatrix matrix, Span<byte> intBuffer)
    {
        WriteInt(destination, intBuffer, matrix.NonzeroCount);
        destination.Write(matrix.AsReadOnlySpan());
    }


    private static void WriteInt(MemoryStream destination, Span<byte> intBuffer, int value)
    {
        BinaryPrimitives.WriteInt32BigEndian(intBuffer, value);
        destination.Write(intBuffer);
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership transfers to the returned RawR1csInstance.")]
    private static RawR1csInstance DeserialiseInstance(byte[] data)
    {
        int offset = 0;
        int rowCount = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset, 4)); offset += 4;
        int columnCount = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset, 4)); offset += 4;
        int publicInputCount = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset, 4)); offset += 4;

        R1csMatrix a = DeserialiseMatrix(data, ref offset, rowCount, columnCount);
        R1csMatrix b = DeserialiseMatrix(data, ref offset, rowCount, columnCount);
        R1csMatrix c = DeserialiseMatrix(data, ref offset, rowCount, columnCount);

        int scalarSize = Scalar.SizeBytes;
        ReadOnlySpan<byte> publicInputs = data.AsSpan(offset, publicInputCount * scalarSize);

        return RawR1csInstance.Create(a, b, c, publicInputs, SensitiveMemoryPool<byte>.Shared);
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership transfers to the returned R1csMatrix; the caller passes it to RawR1csInstance.Create which takes ownership.")]
    private static R1csMatrix DeserialiseMatrix(byte[] data, ref int offset, int rowCount, int columnCount)
    {
        int scalarSize = Scalar.SizeBytes;
        int nnz = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset, 4)); offset += 4;
        int matrixSize = R1csMatrix.ComputeBufferSize(nnz, CurveParameterSet.Bls12Curve381);
        //R1csMatrix's stored buffer is (rowIndices, colIndices, values). Extract back into the
        //typed factory.
        int[] rows = new int[nnz];
        int[] cols = new int[nnz];
        byte[] values = new byte[nnz * scalarSize];
        for(int i = 0; i < nnz; i++)
        {
            rows[i] = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset + i * sizeof(int), sizeof(int)));
        }
        for(int i = 0; i < nnz; i++)
        {
            cols[i] = BinaryPrimitives.ReadInt32BigEndian(data.AsSpan(offset + nnz * sizeof(int) + i * sizeof(int), sizeof(int)));
        }
        data.AsSpan(offset + 2 * nnz * sizeof(int), nnz * scalarSize).CopyTo(values);
        offset += matrixSize;

        return R1csMatrix.FromSortedTriples(rows, cols, values, rowCount, columnCount, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
    }


    [SuppressMessage("Reliability", "CA2000", Justification = "Ownership transfers to the returned RawR1csWitness.")]
    private static RawR1csWitness DeserialiseWitness(byte[] data, RawR1csInstance instance)
    {
        int scalarSize = Scalar.SizeBytes;
        int witnessCount = instance.A.ColumnCount - 1 - instance.PublicInputCount;
        int expected = witnessCount * scalarSize;
        if(data.Length != expected)
        {
            throw new InvalidOperationException(
                $"Fixture witness has {data.Length} bytes but the instance shape requires {expected}.");
        }

        return RawR1csWitness.FromCanonical(data, CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
    }


    private static SpartanProof DeserialiseProof(byte[] data, RawR1csInstance instance)
    {
        int rowVariableCount = BitOperations.Log2((uint)instance.A.RowCount);
        int columnVariableCount = BitOperations.Log2((uint)instance.A.ColumnCount);
        HyraxCommitmentDimensions dimensions = HyraxCommitmentDimensions.ForVariableCount(columnVariableCount);
        int ipaRoundCount = BitOperations.Log2((uint)dimensions.ColumnCount);

        //The error commitment is built over the row variables (ForVariableCount
        //of the row-variable count); its IPA round count is log_2 of that
        //commitment's column count.
        HyraxCommitmentDimensions errorDimensions = HyraxCommitmentDimensions.ForVariableCount(rowVariableCount);
        int errorIpaRoundCount = BitOperations.Log2((uint)errorDimensions.ColumnCount);

        return SpartanProof.FromBytes(
            data, dimensions.RowCount, rowVariableCount, columnVariableCount, ipaRoundCount, errorIpaRoundCount,
            CurveParameterSet.Bls12Curve381, SensitiveMemoryPool<byte>.Shared);
    }


    private static void WriteCanonical(BigInteger value, Span<byte> destination)
    {
        destination.Clear();
        BigInteger r = Bls12Curve381BigIntegerScalarReference.FieldOrder;
        BigInteger nonNegative = ((value % r) + r) % r;
        if(!nonNegative.TryWriteBytes(destination, out int written, isUnsigned: true, isBigEndian: true))
        {
            throw new InvalidOperationException("Reduced scalar did not fit in the canonical span.");
        }

        if(written < destination.Length)
        {
            int shift = destination.Length - written;
            destination[..written].CopyTo(destination[shift..]);
            destination[..shift].Clear();
        }
    }
}